#!/usr/bin/env bash


python /Users/jubanjanmacbook/PycharmProjects/502_Project/SER502-Spring2020-Team26/src/runtime/lexer.py

echo "Done with Lexical Analysis!"

swipl /Users/jubanjanmacbook/PycharmProjects/502_Project/SER502-Spring2020-Team26/src/runtime/program.pl




